- adafruit_display_text/label.py
same issue as
https://github.com/adafruit/Adafruit_CircuitPython_PyPortal/issues/14
>  fix calls to displayio.TileGrid usage of position

- adafruit_display_text/label.py
Greetings. Regarding the part of [PyPortal set_text speed (and line-spacing)?](
https://forums.adafruit.com/viewtopic.php?f=60&t=148356) about the default line spacing for multi-line text, I managed to override the `_line_spacing` property on my text area to a much denser value.
The image below shows the result of the tighter spacing.
Making a PR to allow users to set their own line spacing without using private properties, and keeping the default line spacing of 1.25. Thanks for any feedback.
> Enabling users to set line spacing for multi-line labels

- examples/display_text_textarea_boundingbox.py
tried this stock on pyportal and did not work as the api no longer supports position as a kwarg for the location. fixed with simple re-naming.
> updating to 4.0.1

- README.rst
- examples/display_text_simpletest.py
Update simple example and usage example in readme, additional line after imports for pep 8.
As mentioned in #15 the simplest test example was blank although there was a good example in the readme file. I update the simple test file to match the usage example in the readme file and also put the display updating call in a `while True:` loop so a user will be sure to see the output.
I also added an additional blank line after the import statements in that file for pep 8 compliance. I also then copied that code to the usage example in the readme so that the update is reflected there.
I built the docs to verify the changes were reflected there, they were and I saw no other relevant aspect of the docs that needed updating. Even though the simple test file was blank the docs were already …
> Update simple example and usage example in readme

- .gitignore
- examples/display_text_pyportal.py
> Updated PyPortal example to work with latest stable CircuitPython

- adafruit_display_text/label.py
I have added "cx" and "cy" property to the label, such that setting those will move the center of the text rather than the top left corner of the text. My apologies if it is already available. 
Eg. for PyPortal 
```python
timeDisplay = label.Label(font,text='12:60:60',color=color)
timeDisplay.cx = 160 
timeDisplay.cy = 120
```
> Added "cx" and "cy" property to the label to change center of Label

- adafruit_display_text/label.py
Allows for providing float object, such as acceleration or gyro data, without needing to convert to string in user code.
> Convert text object to string.

- adafruit_display_text/label.py
Resolves issue where text value evaluates to False, label will not display.
Tested with proximity data that returns 0 when no object is present.
> Fixes issue where label will not display when value is False

- adafruit_display_text/label.py
This fixes an issue when assigning x and y when initializing a Label instance that caused x and y to go to 0.
> Added x and y as keyword arguments.

- adafruit_display_text/label.py
- examples/display_text_background_color.py
This change allows you to set background_color of the label in the constructor or with a property. Setting background_color to false, or excluding it entirely will result in same current behavior which is transparent background. This is referenced in issue #33.
> Adding background_color

- adafruit_display_text/label.py
- examples/display_text_anchored_position.py
- I found an error in the calculations for the `anchor_position` getter and setter, that incorrectly placed the x,y locations based on the specified `anchor_point` and `anchor_position`.  I updated these calculations to be correct.
- I updated the `anchor_point` setter so that the x,y positions are recalculated upon a change to anchor_point.  
- I updated the example/display_text_anchored_position.py so that the tested anchor positions are directly at the edge and corners of the display
- Updated the `font` and `text` setters such that `anchored_position` is properly updated.
Verification:
I verified on an ItsyBitsy NRF52840 running an ILI9341 display 320x240 pixels running the Adafruit display driver.
Other impacts:
This update may "break" existing projects using `label` since the …
> Fix anchor_position getter/setter, anchor_point setter and display_text_anchored_position example

- adafruit_display_text/label.py
The problem:  Current label's bounding_box does not including the pixels for trailing whitespace (or any glyphs that rely on the font's "shift_x" parameter).  So, if you create a label and then use the bounding_box to set the next bit of text, then any spaces will seem like they weren't ever printed.
The fix: The "right" parameter for the bounding_box is updated to include any "glyph.shift_x", for example when a trailing whitespace is present.  This will ensure that any glyphs that used "shift_x" will be accounted-for in the right edge of the bounding_box.
Potential negative impacts:  Could mess up someone's label placement if they are already accounting for this missing space at the end.
> Updated bounding_box "right" value to include trailing whitespace

- adafruit_display_text/label.py
Solves #11
This will show a more helpful message when user tries to set text to a string that is too long.
> catch group full exception and re-raise with more descriptive message

- adafruit_display_text/label.py
- examples/display_text_background_color_padding.py
When using imported BDF font files with proportional typefaces, the current version of label with applied background color only covers the glyphs but not the whitespace.  Also, spaces provide some errant dots.  See image:
This PR creates an additional colored bitmap tileGrid as the bottom layer below the text that is the size of the bounding box around the glyph text.  The following three images show examples of the proposed PR with differing text.
Note: The bounding box is a simple minimum bounding box to fit the whole set of glyphs.  This means that text with no ascenders and descenders (see second image below `mere a or o`) will have a smaller bounding box than other lines with taller letters.
Possible enhancements:
* Draw a bounding box the same height for all characters, to cover the …
> Updated background color handling for label

- adafruit_display_text/label.py
For #50. Adds a simple check to make sure the glyph is not a NoneType.
```python
Adafruit CircuitPython 5.3.0 on 2020-04-29; Adafruit Circuit Playground Bluefruit with nRF52840
>>> from adafruit_bitmap_font import bitmap_font
>>> from adafruit_display_text import label
>>> font = bitmap_font.load_font("/monoMMM_5_90.bdf")
>>> my_label = label.Label(font, text="hello", color=0xFFFFFF)
>>> 
```
> Add NoneType check for glyph height

- adafruit_display_text/label.py
- examples/display_text_anchored_position.py
It appears as a result of https://github.com/adafruit/Adafruit_Blinka_Displayio/pull/23 fixing displayio, it stopped mocking displayio and actually used real code, so this PR fixes those things.
> Fixed PyLint issues

- adafruit_display_text/label.py
Issue was originally raised here: https://forums.adafruit.com/viewtopic.php?f=60&t=166798
This change will always include `+1` to the value it passes for `max_size` to the super class Group. The extra one accounts for the background tilegrid which was introduced recently to fix background color for custom fonts. This way it does not matter whether the user passes `text` or `max_glyphs` in the constructor, the behavior is the same both ways.
Crash with current version and fix with new version tested with this:
```python
import board
from adafruit_display_text import label
text = "Hello"
text_area = label.Label(terminalio.FONT, max_glyphs=5)
text_area.x = 10
text_area.y = 10
text_area.text = text
board.DISPLAY.show(text_area)
while True:
pass
```
> fix max_glyphs count when text wasn't passed in constructor

- adafruit_display_text/label.py
This attempts to solve #55 
It turned out there were a few issues with the existing handling of anchored position leading to it not working correctly with scale. 
- As noted on a comment in #55 the scale parameter in `__init__()` was actually belonging to the super class Group which does allow it to visually scale the text properly. But Label itself was not remembering or doing anything with the scale.
- The math in the `anchored_position` setter was taking into account the current (x, y) position of the label when determining the new one. But I don't think this is needed, the only things needed to determine the new position should be: the new desired coordinates, the anchor_point, and the width and height.
These changes resolve those issues by keeping the scale in `self._scale` and …
> fix for anchored_position to work correctly with scaled label

- adafruit_display_text/label.py
Resolving zero-sized bitmap identified in issue #58.
To include a colored background for text, a single bitmap (in a TileGrid) is used as the first element of the display group.  The first item is this background bitmap, and the remaining items are TileGrid elements, each with one character of text.
To overcome the zero-sized bitmap, I updated the initial instancing of the TileGrid to include a non-zero sized bitmap (single pixel).  
Note: This initial instance in the group is a place holder that is later updated to the correct size after all the text is created.  An alternate approach could be to create all the text TileGrids, then create the bitmap and insert it into the first position of the group.  Also, do we need to check for a zero-sized `box_width` and `box_height` before setting …
> Bitmap zero - Creates 1-pixel bitmap during initialization of tilegrid for background of label

- adafruit_display_text/label.py
This update ensures that glyph.width and glyph.height are > 0.  For some BDF font files, the spaces can be generated as zero-width.  This change will ensure that no tileGrid is created for zero-width glyphs.
> Check for zero width/height glyphs

- adafruit_display_text/label.py
After changing the code to eliminate the generation of zero-width/zero-height tileGrids, an error arose related to indexing into the tileGrid for characters that were unchanged, see issue: https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/issues/65
This PR updates all tileGrids upon an update to the text.
Impact: With this PR, all characters in the tileGrids are now regenerated upon text change.  This will have a performance impact since all characters are regenerated.  The previous version only updated the tileGrid for changed characters.  The time impact will depend upon how many characters are changed and how many would have remained the same.
> Updated to regenerate all character tileGrids upon text change

- adafruit_display_text/label.py
This is resolves leftover characters as identifed in: https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/issues/67.
The issue was related to the skipping of the tileGrid elements when a blank glyph is present.  I created a different tilegrid_count index to resolve this.
> corrected index replacement of tileGrid, and deletion of unused tileGrids

- adafruit_display_text/label.py
This is to resolve https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/issues/44
This updates the _init_ parameters to allow the `anchor_point` and `anchor_position` to be set when the label is instanced. 
Note: Somehow the diff shows many more changes than expected. Let me know if I need to update my fork to clarify these changes. But to do so I will need to educate myself on exactly how to do the appropriate git incantations.
> Added anchor_point and anchor_position options as parameters

- adafruit_display_text/label.py
> dont create a background bitmap if background_color is None

- adafruit_display_text/label.py
This is to resolve issue https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/issues/80
Some background on label positioning:
There are two ways to specify a label's position, either by `x`,`y` or by `anchor_point` and `anchored_position`.
These two methods could be inconsistent, so I coded this so that setting `anchored_position` actually updates just the x,y locations.  That way we don't have inconsistencies betwee the two.  And the `anchored_position` getter just calculates the value based on the stored `x,y` value.  
However, that means that the positioning of the label will depend upon the order of setting the position.  For example, if you set `x,y` directly, then it will go to that position until you set `anchored_position` to another value.  
In order to keep the …
> Updated label.py to correct position of initial blank text

- adafruit_display_text/label.py
This change improves performance when font glyphs have not been loaded.  See issue: https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/issues/84
On a brief test of plotting the following line of text with Helvetica-Bold-16.bdf, the time to create the label reduced from 9.0 seconds to 0.5625 seconds:
```
my_string = "Welcome to using displayio on CircuitPython!"
```
There was no significant difference in processing time when glyphs had already been loaded.
**Note:** This update will also help with bitmap_label.py
> Include `load_glyphs` of full text string prior to character-processing loop in `_update_text`

- adafruit_display_text/label.py
This resolves #82. The sample script in that issue and several other variations of it that I tested now result in the label remaining in the same position over time.
> Fix anchored position rounding

- adafruit_display_text/label.py
This resolves #87.
Instead of checking if the font was `terminalio.FONT` I opted for `try/except` and ignoring the AttributeError that results from `load_glyphs` not existing. This lets us avoid having to `import terminalio` and does still solve the crash.
> gracefully recover if load_glpyhs does not exist on font we are using

- adafruit_display_text/bitmap_label.py
- adafruit_display_text/label.py
- docs/api.rst
This update makes `text`, `line_spacing` and `scale` mutable.
Other changes:
- Add option to use `bitmap.blit` on CircuitPython builds where the function is available, but will default back to Python blit when not available
Other details on the changes are in a separate post below.
> `bitmap_label`: Make text, line_spacing and scale mutable

- adafruit_display_text/bitmap_label.py
Here are some documentation cleanups that I missed in the previous release.  This deletes the sections about immutability and adds more details to the description about when `save_text` is set to `False`.
> Correct documentation errors related to mutability

- examples/display_text_matrixportal.py
Lots of folks have a Matrix Portal now and are possibly being introduced to `displayio` for the first time with it. See #95 for one example. But I think it's popped up a few other places as well. 
The majority of `displayio` examples are written using `board.DISPLAY` assuming that they will be run on a device with a built-in display. Any written this way won't work as is on a Matrix Portal.
This PR adds a copy of the simpletest example that has been modified to work on Matrix Portal.
I do wonder if we want to keep the examples seperated like in this PR, or combined into one file with comment / uncomment a section? Or perhaps there is some other possible technical solution that can work with both types of devices without the user having to worry about it as much?
> Add matrixportal example

- examples/display_text_magtag.py
This adds an example that is adapted to run on the MagTag. 
Here is how it looks on the display:
> Adding MagTag example

- adafruit_display_text/__init__.py
- examples/display_text_wraptest.py
I think this helper function was originally the PyPortal library.
If we move it to here we can make use of it in all of the various different portal libraries as well as directly from user code. This will make it easier to wrap text for different sized displays.
> Wrapping helper function

- adafruit_display_text/__init__.py
Fixes #104. This now works on short text when the max_chars is equal to the text words.
> Fixed wrapping function when text length = maxchars

- adafruit_display_text/bitmap_label.py
- adafruit_display_text/label.py
Each time new glyphs have to be loaded from a font, it can take a long time (hundreds of milliseconds).  Besides which, not all fonts have the "M" character that is used for estimating the ascent.  Instead, use the ascent and descent properties of Font objects, if available. (they are available in bdf and pcf fonts since https://github.com/adafruit/Adafruit_CircuitPython_Bitmap_Font/releases/tag/1.3.0 but terminalio.FONT still doesn't have it)
In particular, before this change the "forkawesome" fonts can't be used, because they have only glyphs starting at Unicode 0xf000 (called the Private Use Area), and may affect webdings/wingdings type fonts as well. (forkawesome fonts converted to pcf are [on my blog](https://emergent.unpythonic.net/01606790241))
This changes the layout of text …
> label: Use new, optional 'ascent', 'descent' properties

- adafruit_display_text/bitmap_label.py
This implements the changes required in `bitmap_label.py` to use the ascent and descent feature which was recently added to `Adafruit_CircuitPython_Bitmap_Font`
The analogous PR for the regular label was #102 
I tested on a PyPortal with this code:
```python
import board
from displayio import Group
from adafruit_display_text import bitmap_label
from adafruit_bitmap_font import bitmap_font
font = bitmap_font.load_font("/fonts/forkawesome-36.pcf")
w,h,dx,dy = font.get_bounding_box()
glyphs = "".join(chr(0xf000 + i) for i in range(8))
group = Group()
label = bitmap_label.Label(font=font, text=glyphs, background_color=0x111111)
label.anchor_point = (0, 0)
label.anchored_position = (0,0)
group.append(label)
board.DISPLAY.show(group)
while True:
pass
```
> Bitmap label ascent descent

- adafruit_display_text/label.py
Adding some documentation functions parameters in functions in label.py. Trying to standardize the documentation with Bitmap_label.py docs. 
New documentation included for:
Label main class
_create_background_box private function
_get_ascent_descent private function
_update_background_color private function
I unfamiliar with the standard for private function classes documentation in CP. for maintainability purposes I think it will be a nice to have.
> Intial review of documentation

- adafruit_display_text/label.py
This is a fix for adafruit/Adafruit_CircuitPython_Display_Text#113 .
It keeps the scale of this outer Label at 1 and passes any scale setting
through to the local_group inside as described in the comments already in
the __init__ method.
> Transfer the scale attribute down to the inner local_group and keep the scale of Label at 1

- adafruit_display_text/bitmap_label.py
Removing usage of `self._scale` in bitmap_label that is causing conflict with Blinka displayio.Group library's internal variable with the same name.  
I verified the code on a PyPortal and also on Blinka.
This is targeted to resolve this issue on Adafruit_Blinka_Displayio https://github.com/adafruit/Adafruit_Blinka_Displayio/issues/45.
Blinka: Currently released version
Blinka: Version with this PR
Test code with Blinka and `pygamedisplay`:
```python
import sys
sys.path.append("./lib")
import time
import random
from adafruit_blinka import board
from blinka_displayio_pygamedisplay import PyGameDisplay
display = PyGameDisplay(width=320, height=240, auto_refresh=False)
#
#from adafruit_display_text import label
from adafruit_display_text import bitmap_label …
```
> Update scale to remove self._scale that conflicts with Blinka

- examples/display_text_background_color.py
- examples/display_text_background_color_padding.py
Found some typos to fix. But mostly hoping this small change will allow the next release to make it to PyPi correctly. It seems when I made the most recent release I mistyped the tag number too low, which caused that upload to PyPi not to work right. 
I tried making a new release with no change, but it seemed to be "stuck" trying to make files containing the previous incorrect version number. Here is the actions results of that attempt: https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/runs/1893413227?check_suite_focus=true
> fix typo in example comment

- adafruit_display_text/label.py
- examples/display_text_label_align_baseline_comparison.py
With this change, we are adding a new parameter called base_alignment in the label library.  Also we are including some tests to compare old behavior vs New behavior. This will address issues #103 and #100. 
For back-compatibility parameter is set to False by default, that way old code created will still function with the new version
> New parameter and example creation for testing and future reference

- adafruit_display_text/bitmap_label.py
- adafruit_display_text/label.py
- examples/display_text_label_align_baseline_comparison.py
There present PR is to include new parameter base_alignment to the bitmap_label. This parameter will allow to align to different bitmap_label along the baseline.  This is similar to the work done on the label library.  
Including in this text the code used to test. Also included a Picture of the results.
As you can see in the picture, including this parameter will allow the user to align both the Label and the bitmap_label at the same time.  If a sample code is needed let me know. I consider that the example for the base_label parameter in label is enough.
@kmatch98 if you can take a look at this, I am guessing that you are the writer of this library.  So any input would be appreciated.
And sorry again for the fonts :)
Test code @FoamyGuy I know my test are complicated ;)
```
import time …
```
> Bitmap label base alignment

- adafruit_display_text/__init__.py
- examples/display_text_wrap_pixels_test.py
Jeff wrote this nice helper function for wrapping text to a number of pixels instead of characters.
This PR adds that function as well as an example that illustrates it's usage.
One quirk worth consideration is that the new wrap_by_pixels function returns a string with newlines inserted. Whereas the older wrap_by_characters function returns a list of the lines, and joining with the newline is left up to the code using it. I think I like the way this one does it better with the string. But the other one came from the PyPortal libraries originally, perhaps there is something in them that is using the list. Maybe it would be worthwhile to add a parameter to both that controls this behavior?
> Adding the wrap_by_pixels function

- adafruit_display_text/bitmap_label.py
For font files that have `ASCENT`/`DESCENT` that is incompatible with the glyph dimensions and y-offsets, this clips the top of any offending glyphs and provides a warning.
This is to resolve https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/issues/129
> clip glyphs that exceed ascent property

- adafruit_display_text/__init__.py
- adafruit_display_text/bitmap_label.py
- adafruit_display_text/label.py
To replace PR #121. Testing code is the same as used in previous PR
Tested with bitmap_label and label. Similar results as PR #121 showed.  Included corrections from @kmatch98 in that PR.
@FoamyGuy as discussed please review.
> Tab replacement corrections

- adafruit_display_text/label.py
This change addresses cases when Label class is initialized with
max_glyphs instead of text. In such cases, the split function is
attempted on None object instead of an empty string:
File "/lib/adafruit_display_text/label.py", line 84, in __init__
AttributeError: 'NoneType' object has no attribute 'split'
Fixes: https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/issues/141
> label.py: Fix Label when initial text is not provided

- adafruit_display_text/__init__.py
- adafruit_display_text/bitmap_label.py
- adafruit_display_text/label.py
This replace PR #124. Will solve isssue #100.
Logic was tested in Previous PR.  It was tested again using the blinka display for label and bitmap label
These are the results after refactoring. Using the same code presented in PR #124 
@FoamyGuy Please review with code in previous PR. Thanks :)
> Anchoring Point relative to the Baseline

- adafruit_display_text/__init__.py
- adafruit_display_text/bitmap_label.py
- docs/api.rst
* Show adafruit_display_text in the API Reference. This makes BaseLabel visible.
* Change the header in bitmap_label so that it matches the format in label.
* Other minor tweaks.
If we don't want BaseLabel to be visible in the online documentation, just close this PR.
> Add BaseLabel to the online documentation

- adafruit_display_text/__init__.py
After some verification, I add the ``**kwargs`` arguments to the LabelBase.
This was tested using slightly modified simple test to include and additional argument. will close #146 
```python
import board
from adafruit_display_text import label
text = "Hello world"
text_area = label.Label(terminalio.FONT, text=text, WeTheNorth=True)
text_area.x = 10
text_area.y = 10
board.DISPLAY.show(text_area)
while True:
pass
```
```python 
Adafruit CircuitPython 6.2.0-beta.4 on 2021-03-18; Seeeduino Wio Terminal with samd51p19
>>> import code
```
```python
Adafruit CircuitPython 6.2.0-beta.4 on 2021-03-18; Seeeduino Wio Terminal with samd51p19
>>> import code
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "code.py", line 10, in <module>
File …
```
> Solving kwargs arguments verifications

- adafruit_display_text/__init__.py
- adafruit_display_text/bitmap_label.py
- adafruit_display_text/label.py
This will make info on the font ascent/descent info available for the class, avoiding unnecessary calls to calculate this during the script
> Ascent_Descent information at start

- docs/examples.rst
- examples/display_text_advance_example.py
Adding a new advanced example that includes all the parameters features.
> Library Advanced example and tests

- adafruit_display_text/bitmap_label.py
This will correct some small glitches with the anchor point for bitmap_label for the UPR and DWR direction
```python
import board
from adafruit_display_text import bitmap_label
from adafruit_bitmap_font import bitmap_font
display = board.DISPLAY
main_group = displayio.Group(max_size=10)
MEDIUM_FONT = bitmap_font.load_font("fonts/Helvetica-Bold-16.bdf")
LINE_HOR = displayio.Bitmap(4, display.height, 2)
LINE_VER = displayio.Bitmap(display.width, 4, 2)
COLOR = 0x990099
palette = displayio.Palette(2)
palette[0] = 0x004400
palette[1] = 0x00FFFF
text_area_UPR = bitmap_label.Label(MEDIUM_FONT,
text="Upwards-1.0",
label_direction="UPR",
background_color=COLOR,
anchored_position=(200, 200),
anchor_point=(1.0, 1.0),
)
text_area_UPR2 = bitmap_label.Label(MEDIUM_FONT, …
```
> correcting_anchor_point for bitmap_label Upwards and Downwards direction

- .pre-commit-config.yaml
- adafruit_display_text/__init__.py
- adafruit_display_text/bitmap_label.py
- adafruit_display_text/label.py
- examples/display_text_advance_example.py
- examples/display_text_anchored_position.py
- examples/display_text_background_color_padding.py
- examples/display_text_label_vs_bitmap_label_comparison.py
- examples/display_text_pyportal.py
- examples/display_text_wrap_pixels_test.py
Closes #131
Remove the `max_size` parameter from `Label` and `BitmapLabel` now that it has been disabled in `shared-bindings`.
This has been tested with:
```
Adafruit CircuitPython 6.3.0 on 2021-06-01; Adafruit PyPortal with samd51j20
```
> Remove max_size parameter

- adafruit_display_text/bitmap_label.py
Formerly it was possible to access the Bitmap object that is drawn into by BitmapLabel. The [Dial widget makes use of this](https://github.com/adafruit/Adafruit_CircuitPython_DisplayIO_Layout/blob/cb263f13f09f3f42cb3183774cbf3bc1c46a4883/adafruit_displayio_layout/widgets/dial.py#L794) in order to apply rotation to labels using `bitmaptools.rotozoom()` 
This PR adds a `bitmap` property for BitmapLabel that restores access to it.
> bitmap property for bitmap_label

- adafruit_display_text/bitmap_label.py
This PR should address Issue #157 but I don't have the hardware to test, just followed the code to figure out what was happening.  Use of local variable `text` instead of `self._text` should fix the issue.
> Fix error from save_text = False

- adafruit_display_text/__init__.py
- adafruit_display_text/bitmap_label.py
- adafruit_display_text/label.py
- docs/conf.py
- docs/requirements.txt
Found some type hints were missing and some docstrings could use some tweaks, so just a PR to address those!
> Update type hints

- adafruit_display_text/__init__.py
This resolves https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/issues/162
Note: I had to disable "too-many-nested-blocks" to get it to pass pylint.  I agree that the logic is difficult to follow, requiring a refactor of the whole thing to resolve (but I'm passing the technical debt forward for now).
My test code:
```python
from adafruit_display_text import bitmap_label, wrap_text_to_pixels
text_string = "CircuitPython is a programming language designed to simplify experimenting and learning to code on low-cost microcontroller boards."
text_string=text_string+("\n\nWith CircuitPython, there are no upfront desktop downloads needed. Once you get your board set up, open any text editor, and start editing code. It's that simple.")
text_string = "CircuitPython …
```
> Resolve missing spaces when long words wrap across a full line.

- adafruit_display_text/scrolling_label.py
- examples/display_text_scrolling_label.py
This adds a new `ScrollingLabel` that is a fixed-width label that can scroll the text leftward like a marquee.
An example has been provided to show the most basic usage.
This component is used in my PyPortal Winamp player project but I figured this piece is generic enough to re-used for other purposes.
> Adding ScrollingLabel

- adafruit_display_text/__init__.py
- adafruit_display_text/bitmap_label.py
1. `bitmap_label.Label` - the `self._bitmap` and `self._tilegrid` is no longer recreated all the time
1. This makes it more efficient for updates for text have the _same length_ particularly in terms of avoiding creating a new `Bitmap` (and `TileGrid`) using more memory briefly and potentially causing memory fragmentation.
2. Adding a new `self._prev_label_direction` to support `label_direction` properly.
4. Fixed an unrelated bug in `label_direction` for `RTL` which would toggle direction if the value was repeatedly set - text reversal is now performed as text is set and not stored.
5. `_replace_tabs()` function also enhanced to only do split/join if tabs are present - this is probably a rare case and it's inefficient to be making new text strings all the time. 
The most efficient …
> Improved memory efficiency for some text updates to bitmap_label.Label

- adafruit_display_text/bitmap_label.py
In the latest release, setting the text to an empty string, then back to a string of the same size as the previous (non-empty) value, the bitmap label would not be updated, remaining invisible until its size changed. [See this code for example](https://github.com/adafruit/Adafruit_CircuitPython_MacroPad/blob/main/examples/macropad_grid_layout.py). This is because `self._bitmap` was still set, with the right size, so was `self._tilegrid`, so `self._local_group` remained empty.
(Also one use of `self._text` instead of `text` fixed).
> Free the bitmap when set to empty string

- adafruit_display_text/scrolling_label.py
- docs/api.rst
- docs/examples.rst
- requirements.txt
- setup.py
> Add typing and documentation for ScrollingLabel

- adafruit_display_text/__init__.py
- adafruit_display_text/bitmap_label.py
- adafruit_display_text/label.py
- adafruit_display_text/scrolling_label.py
Resolves #172 by using `fontio.FontProtocol` for type annotations instead of that huge `Union`.
> Use `fontio.FontProtocol` for type annotations

- adafruit_display_text/bitmap_label.py
Please see my comment on issue #169
> Fix for bitmap_label losing direction - bug #169

- adafruit_display_text/bitmap_label.py
- adafruit_display_text/label.py
Hi,
This PR solves Label can take Tuple[int, int, int] for color #175 
Both parameters, `color` and `backgrount_color` can take either an int or a Tuple[int, int, int].
I tested label and bitmap_label with the Adafruit Feather RP2040 and the ST7789 display.
Please let me know if you have any comments!
Thanks!
> Corrected typing to allow the color arguments to also take a Tuple

- adafruit_display_text/__init__.py
Setting a label's text to a string containing unprintable characters doesn't error but has the character ignored.
Calling wrap_text_to_pixels() on the same string however raises an error.
Test code:
```py
import board
import time
from adafruit_display_text.label import Label
from adafruit_display_text import wrap_text_to_pixels
display = board.DISPLAY
label = Label(x=0, y=20, font=terminalio.FONT, color=0xFFFFFF, scale=4)
display.show(label)
TEST_STRING = "--§§--\r\n--"
label.text = TEST_STRING
time.sleep(1)
out = wrap_text_to_pixels(
TEST_STRING,
font=terminalio.FONT,
max_width=64
)
label.text = "\n".join(out)
while True: pass
```
Before:
```py
Traceback (most recent call last):
File "code.py", line 19, in <module>
File …
```
> Ignore characters that are not printable in wrap_text_to_pixels

- adafruit_display_text/bitmap_label.py
- adafruit_display_text/label.py
This fixes an issue that resulted in multiple labels using monospace fonts with different leading characters to not align properly if the shift x values from the bounding box property in the font is different for different characters. 
The change hardcodes the left value to start at 0 rather than the shift x value which was actually causing the shift to get "cut out" and no included in the final bitmap, as well as causing alignment to become misaligned with other labels placed at the same x position.
This problem was original reported on the forums here: https://forums.adafruit.com/viewtopic.php?p=954011
There are details and photos in that forum post. 
Here are some photos illustrating the difference with this proposed change:
Currently released version:
This PR version:
If adopted this …
> fix left edge location for first character of the label.

- adafruit_display_text/__init__.py
- adafruit_display_text/bitmap_label.py
Related to #171 
tested with:
```python
import time
import board
from adafruit_display_text import bitmap_label
display = board.DISPLAY
main_group = displayio.Group()
MEDIUM_FONT = bitmap_font.load_font("LeagueSpartan-Bold-16.bdf")
TIME_PAUSE = 1
text_area = bitmap_label.Label(terminalio.FONT, x=20, y=20, text="Verbose Option Testing", verbose=True)
main_group.append(text_area)
display.show(main_group)
time.sleep(TIME_PAUSE)
text_area.text = "Testing Verbose=True"
text_initial_specs = bitmap_label.Label(
MEDIUM_FONT,
text="Verbose",
x=display.width // 2,
y=display.height // 2,
verbose=True,
)
main_group.append(text_initial_specs)
display.show(main_group)
time.sleep(TIME_PAUSE)
main_group.pop()
text_area.text = "Testing Verbose=False"
print("putting the …
```
> adding_verbose_option

- adafruit_display_text/bitmap_label.py
When adding padding to a bitmap label and setting its anchored_position, the location of the label is incorrect.
This fixes the calculation, and makes bitmap labels display the same way as labels when possible.
Note: I assumed that the intention is for the position to be based on the corner of the text, and not the full box.
The first test shows each label.Label in grey (correctly placed), and the bitmap_label.Label in color on top of it.
The other test shows the fixed bitmap_label.Label in green on top of the old one in red.
Before
After
Here are DWR and UPR bitmap_label, fixed in green on top of the current ones in red. (No comparison with label.Label because or #185 which should be fixed on its own).
```py
from adafruit_gizmo import tft_gizmo
display = tft_gizmo.TFT_Gizmo()
from …
```
> Fix the position of bitmap_label with padding and anchored_position

- adafruit_display_text/bitmap_label.py
Fixes #183
The bounding box was ignoring multiple `\n` by only setting a bool when encountering one.
Did some tests with anchored positions to confirm it matched the label version.
(Which includes the fact that ending the label with empty lines is ignored).
> Fix multiple lines in bitmap label causing an error

- adafruit_display_text/label.py
closes #185 
Test code almost the same as previous PR by Neradoc
```python
from adafruit_display_text import label, bitmap_ll
import time
import vectorio
import board
display = board.DISPLAY
splash = displayio.Group(x=1, y=1, scale=3)
display.show(splash)
display.auto_refresh = False
color_palette = displayio.Palette(3)
color_palette[0] = 0x008000  # Bright Green
color_palette[1] = 0x808080 # 0xAA0088
color_palette[2] = 0x000022
lines = displayio.Group()
for num in range(21):
y = 10 * num
if num % 5 == 0:
COLOR = 0
else:
COLOR = 1
lines.append(vectorio.Rectangle(pixel_shader=color_palette,
width=display.width, height=1, x=0, y=y, color_index=COLOR,
))
lines.append(vectorio.Rectangle(pixel_shader=color_palette,
width=1, height=display.height, x=y, y=0, …
```
> fixing label padding

- adafruit_display_text/scrolling_label.py
This resolves #182 
As was noted on a comment in the issue `full_text` was the property that was used to change the text rather than `text` like it is with BitmapLabel and Label. So the functionality to change text after creation does exist, but the property name used to do it is not the same as it is on the other Label types.
This was original done that way because I didn't know how to override parent properties while still being able to use the parent implementation of the property in some other parts of code. It turned out that we skirted around that issue by being able to call the internal `_set_text()` function directly rather than using the parents properties.
The change in this PR makes it so that `scrolling_lbl.text` will now function the same as `scrolling_lbl.full_text` which …
> override text property from parent on ScrollingLabel

- adafruit_display_text/__init__.py
- adafruit_display_text/bitmap_label.py
- adafruit_display_text/label.py
- adafruit_display_text/scrolling_label.py
- docs/conf.py
> updating FontProtocol link to Circuitpython RTD

- adafruit_display_text/bitmap_label.py
- docs/conf.py
This adds support for the change this core pr: https://github.com/adafruit/circuitpython/pull/8136
There is still fallback logic so that devices that aren't on the same versions can still both work with the library
> bitmaptools.blit refactor support

- adafruit_display_text/bitmap_label.py
resolves: #193 
Clamps x value to positive so that it will not attempt to blit out of bounds
> clamp x value to positive

- adafruit_display_text/bitmap_label.py
in some cases, bitmaptools may not even be used - such as when displayio.Bitmap supports blit.  in others, the module can run without bitmaptools as it has a fallback which works even if it's slower
fixes #192 
tested by ensuring the circuitplayground express - which seems to omit `bitmaptools` - can still blit even if it's slow
> chore: allow use of bitmap_label without bitmaptools

- adafruit_display_text/__init__.py
When I was trying to align other elements relative to the label, I found out that the `width` and `height` properties were out of the place in comparison to the actual bounding box.
To better illustrate that, I wrote a small function that draws the bounding box of the label, to better visualize the problem.
---
<details><summary>Before/after comparison on a 2.2" TFT display</summary>
<p>
</p>
</details> 
<details><summary>Code used for the demo</summary>
<p>
```python
import board
import adafruit_ili9341
from adafruit_display_text import bitmap_label, label
from adafruit_display_shapes.line import Line
displayio.release_displays()
display_bus = displayio.FourWire(
board.SPI(), command=board.D10, reset=board.D11, chip_select=board.D12
)
display = …
```
> Fix width/height properties

- adafruit_display_text/scrolling_label.py
- docs/conf.py
- requirements.txt
As described in adafruit/circuitpython#5411 time.monotonic loses precision over time, which eventually causes the scrolling_label animation to occur every time an update method is called. This can result in the scrolling text suddenly speeding up dramatically.
This PR uses supervisor.ticks_ms and adds a bit of logic to watch for the value rolling over instead of time.monotonic() which should resolve the issue. As mentioned  by Dan in the referenced issue, another option would be to use time.monotonic_ns and similarly watch for the rollover, however apparently not all boards support the monotonic_ns method.
> Use adafruit_ticks.ticks_ms for scrolling_label animation

- adafruit_display_text/bitmap_label.py
Fix for https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/issues/207
When `background_tight` is true, the padding parameters should be ignored.
> Fix for background_tight property not working

- adafruit_display_text/scrolling_label.py
Introduces a check to prevent `_set_text` from being called with unchanged content/text.
> Optimize ScrollingLabel update logic to prevent redundant text updates

- adafruit_display_text/scrolling_label.py
- Allowed empty string (`""`) as valid input for the `text` or `full_text` property.
- Forced an immediate update when the `text` or `full_text` property is set, bypassing the `animate_time` delay for instant display updates.
> Allow empty text and update text instantly

- adafruit_display_text/__init__.py
@ladyada 
Resolves: #202 
Remove the `kwargs` and it's only usage. Incidentally it's only usage will effectively get done automatically now that we aren't using the wildcard.
Confirmed on a device that wrong arguments now raise an exception:
```
TypeError: unexpected keyword argument 'max_glyphs'
TypeError: unexpected keyword argument 'anchor_position'
```
> Remove kwargs

- adafruit_display_text/bitmap_label.py
@ladyada 
Resolves: #201 
I tested on PyPortal Titano with the font specified in the issue and confirmed with this change bitmap label no longer cuts off the top and bot of ascenders and descenders. 
I looked into the position offset between Label and Bitmap label mentioned in the issue as well. The root cause of that the code using anchor point and anchor position which take into account the width and height of the bounding box. It turns out that Label and Bitmap label differ in the size that they come up for the height when `background_tight=False` (which is the default value). That difference in size results in a difference of location when placed with the relative anchors. If you use `background_tight=True` for both types then the height will end up the same and thus placement will …
> fix bmp_lbl for ascenders and descenders

- adafruit_display_text/__init__.py
Added a check to skip redundant `_set_text` calls if the text hasn't changed.
> Optimize LabelBase text setter

- adafruit_display_text/text_box.py
These were left over from the initial development.
> Remove debugging prints from TextBox

- adafruit_display_text/scrolling_label.py
Wrapping max_characters in properties and checking for length of text before adding a space to full_text.
This addresses the situation where the text is shorter or equal to the max_characters, which would add a space when shorter or start scrolling unnecessarily when equal to.  Shorter isn't a big deal when left aligned, but it is noticeable when center or right aligned.
> Managing addition of space at end of text

- adafruit_display_text/text_box.py
- examples/display_text_text_box_simpletest.py
Resolves: #221 
`_reset_text()` was erroneously setting the `self._bounding_box` width to the value calculated dynamically instead of the user specified width value.  Which then caused the anchoring math to get thrown off. Height probably suffered from the same bug, but it would only matter if you were not using dynamic height.
This fixes it by setting the width and height to user specified values. I've also updated the TextBox example script to make use of anchor_point and anchored_position which is what I used for testing the fix.
> fix anchored positioning for TextBox
